### ISSUE TITLE
database creation doesn't wait till the databases have been created

### ISSUE THREAD

**Issue by ellis** [ncthbrt/nact-persistence-postgres#6]
I love what you're doing with nact!

I ran into the following error:

```
error: relation "snapshot_store" does not exist
```

It appears to be because `this.db.none(create(tablePrefix))` hasn't completed before later calls try to access the database.  Would it be possible to await for completion of database creation before returning from `start()`?

When I force my program to sleep for a second after calling `start(...)`, the error disappears, but that's a very ugly hack...

**Comment by ncthbrt** [comment]
Thanks @ellis
In my view it's important that the `start()` command be synchronous as it simplifies getting started with nact quite a bit. Is there a way to run a postgres query synchronously? 

Another thought might be change the db object to be a promise and have all other functions  await on it:
```async
constructor (connectionString, { createIfNotExists = true, tablePrefix = '', ...settings } = {}) {
    super();
    this.tablePrefix = tablePrefix;
    this.db = async () => {
      let db = pgp(connectionString);
      if (createIfNotExists) {
         await this.db.none(create(tablePrefix)).catch(console.error);
      }
      return db
    };
}
```

**Comment by ellis** [comment]
I don't know of any simple way to make the postgres call synchronous.  Recently I saw a project that could make functions synchronous on a single thread, but looked like overkill to me.

I'm not sure whether `this.db = async() => ...` is ideal, since it would try to create the tables on each call (if I'm reading it correctly).  Maybe a slight modification to a separate function store the variable?:

```javascript
async getDb() {
    if (this.db) {
        return this.db;
    }

    this.db = pgp(connectionString);
    if (createIfNotExists) {
         await this.db.none(create(tablePrefix)).catch(console.error);
    }
    return this.db
}
```

Your functions for `events`, `persist`, etc already return promises, right?  Then instead of calling `this.db.any(...)`, you could maybe call `const db = await this.getDb(); db.any(...)` or something like that?

**Comment by ncthbrt** [comment]
Sneakily updated suggestion code. @ellis 
Forgot the function application there. Would more or less have the same effect as what you're suggesting as awaiting multiple times on promises returns the cached result.

**Comment by ellis** [comment]
Makes sense, @ncthbrt !

**Comment by ncthbrt** [comment]
@ellis I've released your changes and made the proposed fix to ensure that tables are always  initialized. Thanks for prodding me.

**Comment by ellis** [comment]
Awesome, worked great!
