### ISSUE TITLE
Allow PostgresPersistenceEngine() to accept a pgp connection as an alternative to a connectionString

### ISSUE THREAD

**Issue by ellis** [ncthbrt/nact-persistence-postgres#8]
Could you allow the user to pass an already constructed pgp database to the constructor of `PostgresPersistenceEngine`, as an alternative to a connection string?  The use case is two-fold:

1. I need to connect to a postgres database with some complex SSL options that I can't pack into the connection string.
2. My program needs to query the postgres database apart from Nact, so I keep getting warnings about having multiple connections open.

**Comment by ncthbrt** [comment]
I can certainly add support for that.

**Comment by ncthbrt** [comment]
@ellis Will let you know when I've got a PR available for this.

**Comment by ncthbrt** [comment]
@ellis I've pushed version v7.3.1 to npm 
Please let me know if you encounter any problems with the implementation of your request.

**Comment by ellis** [comment]
Thanks, @ncthbrt, works great!
